//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecat.Shared.DbMgr.BbWs.BbContext {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Context.WSPortType", Namespace="http://context.ws.blackboard/", ConfigurationName="BbWs.BbContext.ContextWSPortType")]
    public interface ContextWSPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://context.ws.blackboard) of message deactivateToolRequest does not match the default value (http://context.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="deactivateTool", ReplyAction="http://context.ws.blackboard/Context/deactivateToolResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Shared.DbMgr.BbWs.BbContext.deactivateToolResponse deactivateTool(Ecat.Shared.DbMgr.BbWs.BbContext.deactivateToolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="deactivateTool", ReplyAction="http://context.ws.blackboard/Context/deactivateToolResponse")]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.deactivateToolResponse> deactivateToolAsync(Ecat.Shared.DbMgr.BbWs.BbContext.deactivateToolRequest request);
        
        // CODEGEN: Generating message contract since the operation initializeVersion2 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="initializeVersion2", ReplyAction="http://context.ws.blackboard/Context/initializeVersion2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Shared.DbMgr.BbWs.BbContext.initializeVersion2Response initializeVersion2(Ecat.Shared.DbMgr.BbWs.BbContext.initializeVersion2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="initializeVersion2", ReplyAction="http://context.ws.blackboard/Context/initializeVersion2Response")]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.initializeVersion2Response> initializeVersion2Async(Ecat.Shared.DbMgr.BbWs.BbContext.initializeVersion2Request request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://context.ws.blackboard) of message loginTicketRequest does not match the default value (http://context.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="loginTicket", ReplyAction="http://context.ws.blackboard/Context/loginTicketResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Shared.DbMgr.BbWs.BbContext.loginTicketResponse loginTicket(Ecat.Shared.DbMgr.BbWs.BbContext.loginTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="loginTicket", ReplyAction="http://context.ws.blackboard/Context/loginTicketResponse")]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.loginTicketResponse> loginTicketAsync(Ecat.Shared.DbMgr.BbWs.BbContext.loginTicketRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://context.ws.blackboard) of message extendSessionLifeRequest does not match the default value (http://context.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="extendSessionLife", ReplyAction="http://context.ws.blackboard/Context/extendSessionLifeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Shared.DbMgr.BbWs.BbContext.extendSessionLifeResponse extendSessionLife(Ecat.Shared.DbMgr.BbWs.BbContext.extendSessionLifeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="extendSessionLife", ReplyAction="http://context.ws.blackboard/Context/extendSessionLifeResponse")]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.extendSessionLifeResponse> extendSessionLifeAsync(Ecat.Shared.DbMgr.BbWs.BbContext.extendSessionLifeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://context.ws.blackboard) of message registerToolRequest does not match the default value (http://context.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="registerTool", ReplyAction="http://context.ws.blackboard/Context/registerToolResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Shared.DbMgr.BbWs.BbContext.registerToolResponse registerTool(Ecat.Shared.DbMgr.BbWs.BbContext.registerToolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="registerTool", ReplyAction="http://context.ws.blackboard/Context/registerToolResponse")]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.registerToolResponse> registerToolAsync(Ecat.Shared.DbMgr.BbWs.BbContext.registerToolRequest request);
        
        // CODEGEN: Generating message contract since the operation getMyMemberships is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getMyMemberships", ReplyAction="http://context.ws.blackboard/Context/getMyMembershipsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Shared.DbMgr.BbWs.BbContext.getMyMembershipsResponse getMyMemberships(Ecat.Shared.DbMgr.BbWs.BbContext.getMyMembershipsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getMyMemberships", ReplyAction="http://context.ws.blackboard/Context/getMyMembershipsResponse")]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.getMyMembershipsResponse> getMyMembershipsAsync(Ecat.Shared.DbMgr.BbWs.BbContext.getMyMembershipsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://context.ws.blackboard) of message getMembershipsRequest does not match the default value (http://context.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="getMemberships", ReplyAction="http://context.ws.blackboard/Context/getMembershipsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Shared.DbMgr.BbWs.BbContext.getMembershipsResponse getMemberships(Ecat.Shared.DbMgr.BbWs.BbContext.getMembershipsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getMemberships", ReplyAction="http://context.ws.blackboard/Context/getMembershipsResponse")]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.getMembershipsResponse> getMembershipsAsync(Ecat.Shared.DbMgr.BbWs.BbContext.getMembershipsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://context.ws.blackboard) of message getRequiredEntitlementsRequest does not match the default value (http://context.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="getRequiredEntitlements", ReplyAction="http://context.ws.blackboard/Context/getRequiredEntitlementsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Shared.DbMgr.BbWs.BbContext.getRequiredEntitlementsResponse getRequiredEntitlements(Ecat.Shared.DbMgr.BbWs.BbContext.getRequiredEntitlementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getRequiredEntitlements", ReplyAction="http://context.ws.blackboard/Context/getRequiredEntitlementsResponse")]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.getRequiredEntitlementsResponse> getRequiredEntitlementsAsync(Ecat.Shared.DbMgr.BbWs.BbContext.getRequiredEntitlementsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://context.ws.blackboard) of message loginToolRequest does not match the default value (http://context.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="loginTool", ReplyAction="http://context.ws.blackboard/Context/loginToolResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Shared.DbMgr.BbWs.BbContext.loginToolResponse loginTool(Ecat.Shared.DbMgr.BbWs.BbContext.loginToolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="loginTool", ReplyAction="http://context.ws.blackboard/Context/loginToolResponse")]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.loginToolResponse> loginToolAsync(Ecat.Shared.DbMgr.BbWs.BbContext.loginToolRequest request);
        
        // CODEGEN: Generating message contract since the operation logout is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="logout", ReplyAction="http://context.ws.blackboard/Context/logoutResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Shared.DbMgr.BbWs.BbContext.logoutResponse logout(Ecat.Shared.DbMgr.BbWs.BbContext.logoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="logout", ReplyAction="http://context.ws.blackboard/Context/logoutResponse")]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.logoutResponse> logoutAsync(Ecat.Shared.DbMgr.BbWs.BbContext.logoutRequest request);
        
        // CODEGEN: Generating message contract since the operation getSystemInstallationId is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getSystemInstallationId", ReplyAction="http://context.ws.blackboard/Context/getSystemInstallationIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Shared.DbMgr.BbWs.BbContext.getSystemInstallationIdResponse getSystemInstallationId(Ecat.Shared.DbMgr.BbWs.BbContext.getSystemInstallationIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSystemInstallationId", ReplyAction="http://context.ws.blackboard/Context/getSystemInstallationIdResponse")]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.getSystemInstallationIdResponse> getSystemInstallationIdAsync(Ecat.Shared.DbMgr.BbWs.BbContext.getSystemInstallationIdRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://context.ws.blackboard) of message loginRequest does not match the default value (http://context.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="login", ReplyAction="http://context.ws.blackboard/Context/loginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Shared.DbMgr.BbWs.BbContext.loginResponse login(Ecat.Shared.DbMgr.BbWs.BbContext.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="login", ReplyAction="http://context.ws.blackboard/Context/loginResponse")]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.loginResponse> loginAsync(Ecat.Shared.DbMgr.BbWs.BbContext.loginRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://context.ws.blackboard) of message getServerVersionRequest does not match the default value (http://context.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="getServerVersion", ReplyAction="http://context.ws.blackboard/Context/getServerVersionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Shared.DbMgr.BbWs.BbContext.getServerVersionResponse getServerVersion(Ecat.Shared.DbMgr.BbWs.BbContext.getServerVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getServerVersion", ReplyAction="http://context.ws.blackboard/Context/getServerVersionResponse")]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.getServerVersionResponse> getServerVersionAsync(Ecat.Shared.DbMgr.BbWs.BbContext.getServerVersionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://context.ws.blackboard) of message emulateUserRequest does not match the default value (http://context.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="emulateUser", ReplyAction="http://context.ws.blackboard/Context/emulateUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Shared.DbMgr.BbWs.BbContext.emulateUserResponse emulateUser(Ecat.Shared.DbMgr.BbWs.BbContext.emulateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="emulateUser", ReplyAction="http://context.ws.blackboard/Context/emulateUserResponse")]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.emulateUserResponse> emulateUserAsync(Ecat.Shared.DbMgr.BbWs.BbContext.emulateUserRequest request);
        
        // CODEGEN: Generating message contract since the operation initialize is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="initialize", ReplyAction="http://context.ws.blackboard/Context/initializeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Shared.DbMgr.BbWs.BbContext.initializeResponse initialize(Ecat.Shared.DbMgr.BbWs.BbContext.initializeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="initialize", ReplyAction="http://context.ws.blackboard/Context/initializeResponse")]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.initializeResponse> initializeAsync(Ecat.Shared.DbMgr.BbWs.BbContext.initializeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://context.ws.blackboard/xsd")]
    public partial class DeactivateToolResultVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] failureErrorsField;
        
        private bool statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failureErrors", IsNullable=true, Order=0)]
        public string[] failureErrors {
            get {
                return this.failureErrorsField;
            }
            set {
                this.failureErrorsField = value;
                this.RaisePropertyChanged("failureErrors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.platform.blackboard/xsd")]
    public partial class VersionVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long versionField;
        
        private bool versionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified {
            get {
                return this.versionFieldSpecified;
            }
            set {
                this.versionFieldSpecified = value;
                this.RaisePropertyChanged("versionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.platform.blackboard/xsd")]
    public partial class CourseIdVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string externalIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string externalId {
            get {
                return this.externalIdField;
            }
            set {
                this.externalIdField = value;
                this.RaisePropertyChanged("externalId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://context.ws.blackboard/xsd")]
    public partial class RegisterToolResultVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] failureErrorsField;
        
        private string proxyToolGuidField;
        
        private bool statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failureErrors", IsNullable=true, Order=0)]
        public string[] failureErrors {
            get {
                return this.failureErrorsField;
            }
            set {
                this.failureErrorsField = value;
                this.RaisePropertyChanged("failureErrors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string proxyToolGuid {
            get {
                return this.proxyToolGuidField;
            }
            set {
                this.proxyToolGuidField = value;
                this.RaisePropertyChanged("proxyToolGuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deactivateTool", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class deactivateToolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ignore;
        
        public deactivateToolRequest() {
        }
        
        public deactivateToolRequest(string ignore) {
            this.ignore = ignore;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deactivateToolResponse", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class deactivateToolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ecat.Shared.DbMgr.BbWs.BbContext.DeactivateToolResultVO @return;
        
        public deactivateToolResponse() {
        }
        
        public deactivateToolResponse(Ecat.Shared.DbMgr.BbWs.BbContext.DeactivateToolResultVO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class initializeVersion2Request {
        
        public initializeVersion2Request() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="initializeVersion2Response", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class initializeVersion2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public initializeVersion2Response() {
        }
        
        public initializeVersion2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginTicket", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class loginTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clientVendorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clientProgramId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loginExtraInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=4)]
        public long expectedLifeSeconds;
        
        public loginTicketRequest() {
        }
        
        public loginTicketRequest(string ticket, string clientVendorId, string clientProgramId, string loginExtraInfo, long expectedLifeSeconds) {
            this.ticket = ticket;
            this.clientVendorId = clientVendorId;
            this.clientProgramId = clientProgramId;
            this.loginExtraInfo = loginExtraInfo;
            this.expectedLifeSeconds = expectedLifeSeconds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginTicketResponse", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class loginTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        public bool @return;
        
        public loginTicketResponse() {
        }
        
        public loginTicketResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="extendSessionLife", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class extendSessionLifeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        public long additionalSeconds;
        
        public extendSessionLifeRequest() {
        }
        
        public extendSessionLifeRequest(long additionalSeconds) {
            this.additionalSeconds = additionalSeconds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="extendSessionLifeResponse", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class extendSessionLifeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        public bool @return;
        
        public extendSessionLifeResponse() {
        }
        
        public extendSessionLifeResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerTool", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class registerToolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clientVendorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clientProgramId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string registrationPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string initialSharedSecret;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("requiredToolMethods", IsNullable=true)]
        public string[] requiredToolMethods;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute("requiredTicketMethods", IsNullable=true)]
        public string[] requiredTicketMethods;
        
        public registerToolRequest() {
        }
        
        public registerToolRequest(string clientVendorId, string clientProgramId, string registrationPassword, string description, string initialSharedSecret, string[] requiredToolMethods, string[] requiredTicketMethods) {
            this.clientVendorId = clientVendorId;
            this.clientProgramId = clientProgramId;
            this.registrationPassword = registrationPassword;
            this.description = description;
            this.initialSharedSecret = initialSharedSecret;
            this.requiredToolMethods = requiredToolMethods;
            this.requiredTicketMethods = requiredTicketMethods;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerToolResponse", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class registerToolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ecat.Shared.DbMgr.BbWs.BbContext.RegisterToolResultVO @return;
        
        public registerToolResponse() {
        }
        
        public registerToolResponse(Ecat.Shared.DbMgr.BbWs.BbContext.RegisterToolResultVO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMyMembershipsRequest {
        
        public getMyMembershipsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMyMembershipsResponse", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class getMyMembershipsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Ecat.Shared.DbMgr.BbWs.BbContext.CourseIdVO[] @return;
        
        public getMyMembershipsResponse() {
        }
        
        public getMyMembershipsResponse(Ecat.Shared.DbMgr.BbWs.BbContext.CourseIdVO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMemberships", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class getMembershipsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userid;
        
        public getMembershipsRequest() {
        }
        
        public getMembershipsRequest(string userid) {
            this.userid = userid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMembershipsResponse", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class getMembershipsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Ecat.Shared.DbMgr.BbWs.BbContext.CourseIdVO[] @return;
        
        public getMembershipsResponse() {
        }
        
        public getMembershipsResponse(Ecat.Shared.DbMgr.BbWs.BbContext.CourseIdVO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRequiredEntitlements", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class getRequiredEntitlementsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string method;
        
        public getRequiredEntitlementsRequest() {
        }
        
        public getRequiredEntitlementsRequest(string method) {
            this.method = method;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRequiredEntitlementsResponse", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class getRequiredEntitlementsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] @return;
        
        public getRequiredEntitlementsResponse() {
        }
        
        public getRequiredEntitlementsResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginTool", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class loginToolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clientVendorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clientProgramId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loginExtraInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=4)]
        public long expectedLifeSeconds;
        
        public loginToolRequest() {
        }
        
        public loginToolRequest(string password, string clientVendorId, string clientProgramId, string loginExtraInfo, long expectedLifeSeconds) {
            this.password = password;
            this.clientVendorId = clientVendorId;
            this.clientProgramId = clientProgramId;
            this.loginExtraInfo = loginExtraInfo;
            this.expectedLifeSeconds = expectedLifeSeconds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginToolResponse", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class loginToolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        public bool @return;
        
        public loginToolResponse() {
        }
        
        public loginToolResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutRequest {
        
        public logoutRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logoutResponse", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class logoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        public bool @return;
        
        public logoutResponse() {
        }
        
        public logoutResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSystemInstallationIdRequest {
        
        public getSystemInstallationIdRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSystemInstallationIdResponse", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class getSystemInstallationIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getSystemInstallationIdResponse() {
        }
        
        public getSystemInstallationIdResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clientVendorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clientProgramId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loginExtraInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=5)]
        public long expectedLifeSeconds;
        
        public loginRequest() {
        }
        
        public loginRequest(string userid, string password, string clientVendorId, string clientProgramId, string loginExtraInfo, long expectedLifeSeconds) {
            this.userid = userid;
            this.password = password;
            this.clientVendorId = clientVendorId;
            this.clientProgramId = clientProgramId;
            this.loginExtraInfo = loginExtraInfo;
            this.expectedLifeSeconds = expectedLifeSeconds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        public bool @return;
        
        public loginResponse() {
        }
        
        public loginResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getServerVersion", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class getServerVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ecat.Shared.DbMgr.BbWs.BbContext.VersionVO unused;
        
        public getServerVersionRequest() {
        }
        
        public getServerVersionRequest(Ecat.Shared.DbMgr.BbWs.BbContext.VersionVO unused) {
            this.unused = unused;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getServerVersionResponse", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class getServerVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ecat.Shared.DbMgr.BbWs.BbContext.VersionVO @return;
        
        public getServerVersionResponse() {
        }
        
        public getServerVersionResponse(Ecat.Shared.DbMgr.BbWs.BbContext.VersionVO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="emulateUser", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class emulateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userToEmulate;
        
        public emulateUserRequest() {
        }
        
        public emulateUserRequest(string userToEmulate) {
            this.userToEmulate = userToEmulate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="emulateUserResponse", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class emulateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        public bool @return;
        
        public emulateUserResponse() {
        }
        
        public emulateUserResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class initializeRequest {
        
        public initializeRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="initializeResponse", WrapperNamespace="http://context.ws.blackboard", IsWrapped=true)]
    public partial class initializeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://context.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public initializeResponse() {
        }
        
        public initializeResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContextWSPortTypeChannel : Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContextWSPortTypeClient : System.ServiceModel.ClientBase<Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType>, Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType {
        
        public ContextWSPortTypeClient() {
        }
        
        public ContextWSPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContextWSPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContextWSPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContextWSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Shared.DbMgr.BbWs.BbContext.deactivateToolResponse Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.deactivateTool(Ecat.Shared.DbMgr.BbWs.BbContext.deactivateToolRequest request) {
            return base.Channel.deactivateTool(request);
        }
        
        public Ecat.Shared.DbMgr.BbWs.BbContext.DeactivateToolResultVO deactivateTool(string ignore) {
            Ecat.Shared.DbMgr.BbWs.BbContext.deactivateToolRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.deactivateToolRequest();
            inValue.ignore = ignore;
            Ecat.Shared.DbMgr.BbWs.BbContext.deactivateToolResponse retVal = ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).deactivateTool(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.deactivateToolResponse> Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.deactivateToolAsync(Ecat.Shared.DbMgr.BbWs.BbContext.deactivateToolRequest request) {
            return base.Channel.deactivateToolAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.deactivateToolResponse> deactivateToolAsync(string ignore) {
            Ecat.Shared.DbMgr.BbWs.BbContext.deactivateToolRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.deactivateToolRequest();
            inValue.ignore = ignore;
            return ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).deactivateToolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Shared.DbMgr.BbWs.BbContext.initializeVersion2Response Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.initializeVersion2(Ecat.Shared.DbMgr.BbWs.BbContext.initializeVersion2Request request) {
            return base.Channel.initializeVersion2(request);
        }
        
        public string initializeVersion2() {
            Ecat.Shared.DbMgr.BbWs.BbContext.initializeVersion2Request inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.initializeVersion2Request();
            Ecat.Shared.DbMgr.BbWs.BbContext.initializeVersion2Response retVal = ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).initializeVersion2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.initializeVersion2Response> Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.initializeVersion2Async(Ecat.Shared.DbMgr.BbWs.BbContext.initializeVersion2Request request) {
            return base.Channel.initializeVersion2Async(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.initializeVersion2Response> initializeVersion2Async() {
            Ecat.Shared.DbMgr.BbWs.BbContext.initializeVersion2Request inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.initializeVersion2Request();
            return ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).initializeVersion2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Shared.DbMgr.BbWs.BbContext.loginTicketResponse Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.loginTicket(Ecat.Shared.DbMgr.BbWs.BbContext.loginTicketRequest request) {
            return base.Channel.loginTicket(request);
        }
        
        public bool loginTicket(string ticket, string clientVendorId, string clientProgramId, string loginExtraInfo, long expectedLifeSeconds) {
            Ecat.Shared.DbMgr.BbWs.BbContext.loginTicketRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.loginTicketRequest();
            inValue.ticket = ticket;
            inValue.clientVendorId = clientVendorId;
            inValue.clientProgramId = clientProgramId;
            inValue.loginExtraInfo = loginExtraInfo;
            inValue.expectedLifeSeconds = expectedLifeSeconds;
            Ecat.Shared.DbMgr.BbWs.BbContext.loginTicketResponse retVal = ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).loginTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.loginTicketResponse> Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.loginTicketAsync(Ecat.Shared.DbMgr.BbWs.BbContext.loginTicketRequest request) {
            return base.Channel.loginTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.loginTicketResponse> loginTicketAsync(string ticket, string clientVendorId, string clientProgramId, string loginExtraInfo, long expectedLifeSeconds) {
            Ecat.Shared.DbMgr.BbWs.BbContext.loginTicketRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.loginTicketRequest();
            inValue.ticket = ticket;
            inValue.clientVendorId = clientVendorId;
            inValue.clientProgramId = clientProgramId;
            inValue.loginExtraInfo = loginExtraInfo;
            inValue.expectedLifeSeconds = expectedLifeSeconds;
            return ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).loginTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Shared.DbMgr.BbWs.BbContext.extendSessionLifeResponse Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.extendSessionLife(Ecat.Shared.DbMgr.BbWs.BbContext.extendSessionLifeRequest request) {
            return base.Channel.extendSessionLife(request);
        }
        
        public bool extendSessionLife(long additionalSeconds) {
            Ecat.Shared.DbMgr.BbWs.BbContext.extendSessionLifeRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.extendSessionLifeRequest();
            inValue.additionalSeconds = additionalSeconds;
            Ecat.Shared.DbMgr.BbWs.BbContext.extendSessionLifeResponse retVal = ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).extendSessionLife(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.extendSessionLifeResponse> Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.extendSessionLifeAsync(Ecat.Shared.DbMgr.BbWs.BbContext.extendSessionLifeRequest request) {
            return base.Channel.extendSessionLifeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.extendSessionLifeResponse> extendSessionLifeAsync(long additionalSeconds) {
            Ecat.Shared.DbMgr.BbWs.BbContext.extendSessionLifeRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.extendSessionLifeRequest();
            inValue.additionalSeconds = additionalSeconds;
            return ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).extendSessionLifeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Shared.DbMgr.BbWs.BbContext.registerToolResponse Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.registerTool(Ecat.Shared.DbMgr.BbWs.BbContext.registerToolRequest request) {
            return base.Channel.registerTool(request);
        }
        
        public Ecat.Shared.DbMgr.BbWs.BbContext.RegisterToolResultVO registerTool(string clientVendorId, string clientProgramId, string registrationPassword, string description, string initialSharedSecret, string[] requiredToolMethods, string[] requiredTicketMethods) {
            Ecat.Shared.DbMgr.BbWs.BbContext.registerToolRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.registerToolRequest();
            inValue.clientVendorId = clientVendorId;
            inValue.clientProgramId = clientProgramId;
            inValue.registrationPassword = registrationPassword;
            inValue.description = description;
            inValue.initialSharedSecret = initialSharedSecret;
            inValue.requiredToolMethods = requiredToolMethods;
            inValue.requiredTicketMethods = requiredTicketMethods;
            Ecat.Shared.DbMgr.BbWs.BbContext.registerToolResponse retVal = ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).registerTool(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.registerToolResponse> Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.registerToolAsync(Ecat.Shared.DbMgr.BbWs.BbContext.registerToolRequest request) {
            return base.Channel.registerToolAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.registerToolResponse> registerToolAsync(string clientVendorId, string clientProgramId, string registrationPassword, string description, string initialSharedSecret, string[] requiredToolMethods, string[] requiredTicketMethods) {
            Ecat.Shared.DbMgr.BbWs.BbContext.registerToolRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.registerToolRequest();
            inValue.clientVendorId = clientVendorId;
            inValue.clientProgramId = clientProgramId;
            inValue.registrationPassword = registrationPassword;
            inValue.description = description;
            inValue.initialSharedSecret = initialSharedSecret;
            inValue.requiredToolMethods = requiredToolMethods;
            inValue.requiredTicketMethods = requiredTicketMethods;
            return ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).registerToolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Shared.DbMgr.BbWs.BbContext.getMyMembershipsResponse Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.getMyMemberships(Ecat.Shared.DbMgr.BbWs.BbContext.getMyMembershipsRequest request) {
            return base.Channel.getMyMemberships(request);
        }
        
        public Ecat.Shared.DbMgr.BbWs.BbContext.CourseIdVO[] getMyMemberships() {
            Ecat.Shared.DbMgr.BbWs.BbContext.getMyMembershipsRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.getMyMembershipsRequest();
            Ecat.Shared.DbMgr.BbWs.BbContext.getMyMembershipsResponse retVal = ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).getMyMemberships(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.getMyMembershipsResponse> Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.getMyMembershipsAsync(Ecat.Shared.DbMgr.BbWs.BbContext.getMyMembershipsRequest request) {
            return base.Channel.getMyMembershipsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.getMyMembershipsResponse> getMyMembershipsAsync() {
            Ecat.Shared.DbMgr.BbWs.BbContext.getMyMembershipsRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.getMyMembershipsRequest();
            return ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).getMyMembershipsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Shared.DbMgr.BbWs.BbContext.getMembershipsResponse Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.getMemberships(Ecat.Shared.DbMgr.BbWs.BbContext.getMembershipsRequest request) {
            return base.Channel.getMemberships(request);
        }
        
        public Ecat.Shared.DbMgr.BbWs.BbContext.CourseIdVO[] getMemberships(string userid) {
            Ecat.Shared.DbMgr.BbWs.BbContext.getMembershipsRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.getMembershipsRequest();
            inValue.userid = userid;
            Ecat.Shared.DbMgr.BbWs.BbContext.getMembershipsResponse retVal = ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).getMemberships(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.getMembershipsResponse> Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.getMembershipsAsync(Ecat.Shared.DbMgr.BbWs.BbContext.getMembershipsRequest request) {
            return base.Channel.getMembershipsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.getMembershipsResponse> getMembershipsAsync(string userid) {
            Ecat.Shared.DbMgr.BbWs.BbContext.getMembershipsRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.getMembershipsRequest();
            inValue.userid = userid;
            return ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).getMembershipsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Shared.DbMgr.BbWs.BbContext.getRequiredEntitlementsResponse Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.getRequiredEntitlements(Ecat.Shared.DbMgr.BbWs.BbContext.getRequiredEntitlementsRequest request) {
            return base.Channel.getRequiredEntitlements(request);
        }
        
        public string[] getRequiredEntitlements(string method) {
            Ecat.Shared.DbMgr.BbWs.BbContext.getRequiredEntitlementsRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.getRequiredEntitlementsRequest();
            inValue.method = method;
            Ecat.Shared.DbMgr.BbWs.BbContext.getRequiredEntitlementsResponse retVal = ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).getRequiredEntitlements(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.getRequiredEntitlementsResponse> Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.getRequiredEntitlementsAsync(Ecat.Shared.DbMgr.BbWs.BbContext.getRequiredEntitlementsRequest request) {
            return base.Channel.getRequiredEntitlementsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.getRequiredEntitlementsResponse> getRequiredEntitlementsAsync(string method) {
            Ecat.Shared.DbMgr.BbWs.BbContext.getRequiredEntitlementsRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.getRequiredEntitlementsRequest();
            inValue.method = method;
            return ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).getRequiredEntitlementsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Shared.DbMgr.BbWs.BbContext.loginToolResponse Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.loginTool(Ecat.Shared.DbMgr.BbWs.BbContext.loginToolRequest request) {
            return base.Channel.loginTool(request);
        }
        
        public bool loginTool(string password, string clientVendorId, string clientProgramId, string loginExtraInfo, long expectedLifeSeconds) {
            Ecat.Shared.DbMgr.BbWs.BbContext.loginToolRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.loginToolRequest();
            inValue.password = password;
            inValue.clientVendorId = clientVendorId;
            inValue.clientProgramId = clientProgramId;
            inValue.loginExtraInfo = loginExtraInfo;
            inValue.expectedLifeSeconds = expectedLifeSeconds;
            Ecat.Shared.DbMgr.BbWs.BbContext.loginToolResponse retVal = ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).loginTool(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.loginToolResponse> Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.loginToolAsync(Ecat.Shared.DbMgr.BbWs.BbContext.loginToolRequest request) {
            return base.Channel.loginToolAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.loginToolResponse> loginToolAsync(string password, string clientVendorId, string clientProgramId, string loginExtraInfo, long expectedLifeSeconds) {
            Ecat.Shared.DbMgr.BbWs.BbContext.loginToolRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.loginToolRequest();
            inValue.password = password;
            inValue.clientVendorId = clientVendorId;
            inValue.clientProgramId = clientProgramId;
            inValue.loginExtraInfo = loginExtraInfo;
            inValue.expectedLifeSeconds = expectedLifeSeconds;
            return ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).loginToolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Shared.DbMgr.BbWs.BbContext.logoutResponse Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.logout(Ecat.Shared.DbMgr.BbWs.BbContext.logoutRequest request) {
            return base.Channel.logout(request);
        }
        
        public bool logout() {
            Ecat.Shared.DbMgr.BbWs.BbContext.logoutRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.logoutRequest();
            Ecat.Shared.DbMgr.BbWs.BbContext.logoutResponse retVal = ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).logout(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.logoutResponse> Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.logoutAsync(Ecat.Shared.DbMgr.BbWs.BbContext.logoutRequest request) {
            return base.Channel.logoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.logoutResponse> logoutAsync() {
            Ecat.Shared.DbMgr.BbWs.BbContext.logoutRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.logoutRequest();
            return ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).logoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Shared.DbMgr.BbWs.BbContext.getSystemInstallationIdResponse Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.getSystemInstallationId(Ecat.Shared.DbMgr.BbWs.BbContext.getSystemInstallationIdRequest request) {
            return base.Channel.getSystemInstallationId(request);
        }
        
        public string getSystemInstallationId() {
            Ecat.Shared.DbMgr.BbWs.BbContext.getSystemInstallationIdRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.getSystemInstallationIdRequest();
            Ecat.Shared.DbMgr.BbWs.BbContext.getSystemInstallationIdResponse retVal = ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).getSystemInstallationId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.getSystemInstallationIdResponse> Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.getSystemInstallationIdAsync(Ecat.Shared.DbMgr.BbWs.BbContext.getSystemInstallationIdRequest request) {
            return base.Channel.getSystemInstallationIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.getSystemInstallationIdResponse> getSystemInstallationIdAsync() {
            Ecat.Shared.DbMgr.BbWs.BbContext.getSystemInstallationIdRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.getSystemInstallationIdRequest();
            return ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).getSystemInstallationIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Shared.DbMgr.BbWs.BbContext.loginResponse Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.login(Ecat.Shared.DbMgr.BbWs.BbContext.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public bool login(string userid, string password, string clientVendorId, string clientProgramId, string loginExtraInfo, long expectedLifeSeconds) {
            Ecat.Shared.DbMgr.BbWs.BbContext.loginRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.loginRequest();
            inValue.userid = userid;
            inValue.password = password;
            inValue.clientVendorId = clientVendorId;
            inValue.clientProgramId = clientProgramId;
            inValue.loginExtraInfo = loginExtraInfo;
            inValue.expectedLifeSeconds = expectedLifeSeconds;
            Ecat.Shared.DbMgr.BbWs.BbContext.loginResponse retVal = ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).login(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.loginResponse> Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.loginAsync(Ecat.Shared.DbMgr.BbWs.BbContext.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.loginResponse> loginAsync(string userid, string password, string clientVendorId, string clientProgramId, string loginExtraInfo, long expectedLifeSeconds) {
            Ecat.Shared.DbMgr.BbWs.BbContext.loginRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.loginRequest();
            inValue.userid = userid;
            inValue.password = password;
            inValue.clientVendorId = clientVendorId;
            inValue.clientProgramId = clientProgramId;
            inValue.loginExtraInfo = loginExtraInfo;
            inValue.expectedLifeSeconds = expectedLifeSeconds;
            return ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Shared.DbMgr.BbWs.BbContext.getServerVersionResponse Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.getServerVersion(Ecat.Shared.DbMgr.BbWs.BbContext.getServerVersionRequest request) {
            return base.Channel.getServerVersion(request);
        }
        
        public Ecat.Shared.DbMgr.BbWs.BbContext.VersionVO getServerVersion(Ecat.Shared.DbMgr.BbWs.BbContext.VersionVO unused) {
            Ecat.Shared.DbMgr.BbWs.BbContext.getServerVersionRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.getServerVersionRequest();
            inValue.unused = unused;
            Ecat.Shared.DbMgr.BbWs.BbContext.getServerVersionResponse retVal = ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).getServerVersion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.getServerVersionResponse> Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.getServerVersionAsync(Ecat.Shared.DbMgr.BbWs.BbContext.getServerVersionRequest request) {
            return base.Channel.getServerVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.getServerVersionResponse> getServerVersionAsync(Ecat.Shared.DbMgr.BbWs.BbContext.VersionVO unused) {
            Ecat.Shared.DbMgr.BbWs.BbContext.getServerVersionRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.getServerVersionRequest();
            inValue.unused = unused;
            return ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).getServerVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Shared.DbMgr.BbWs.BbContext.emulateUserResponse Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.emulateUser(Ecat.Shared.DbMgr.BbWs.BbContext.emulateUserRequest request) {
            return base.Channel.emulateUser(request);
        }
        
        public bool emulateUser(string userToEmulate) {
            Ecat.Shared.DbMgr.BbWs.BbContext.emulateUserRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.emulateUserRequest();
            inValue.userToEmulate = userToEmulate;
            Ecat.Shared.DbMgr.BbWs.BbContext.emulateUserResponse retVal = ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).emulateUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.emulateUserResponse> Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.emulateUserAsync(Ecat.Shared.DbMgr.BbWs.BbContext.emulateUserRequest request) {
            return base.Channel.emulateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.emulateUserResponse> emulateUserAsync(string userToEmulate) {
            Ecat.Shared.DbMgr.BbWs.BbContext.emulateUserRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.emulateUserRequest();
            inValue.userToEmulate = userToEmulate;
            return ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).emulateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Shared.DbMgr.BbWs.BbContext.initializeResponse Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.initialize(Ecat.Shared.DbMgr.BbWs.BbContext.initializeRequest request) {
            return base.Channel.initialize(request);
        }
        
        public string initialize() {
            Ecat.Shared.DbMgr.BbWs.BbContext.initializeRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.initializeRequest();
            Ecat.Shared.DbMgr.BbWs.BbContext.initializeResponse retVal = ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).initialize(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.initializeResponse> Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType.initializeAsync(Ecat.Shared.DbMgr.BbWs.BbContext.initializeRequest request) {
            return base.Channel.initializeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Shared.DbMgr.BbWs.BbContext.initializeResponse> initializeAsync() {
            Ecat.Shared.DbMgr.BbWs.BbContext.initializeRequest inValue = new Ecat.Shared.DbMgr.BbWs.BbContext.initializeRequest();
            return ((Ecat.Shared.DbMgr.BbWs.BbContext.ContextWSPortType)(this)).initializeAsync(inValue);
        }
    }
}
